### ISSUE TITLE
MDV Calculation 

### ISSUE THREAD

**Issue by jstehn** [Milkdog/scion-web#9]
Calculations are incorrect

**Comment by Milkdog** [comment]
Dodge MDV -  ((Charisma + Integrity+ Legend) / 2)
Parry MDV - ((Manipulation + Larceny/Precense/Command + Legend) / 2) + Epic Manipulation AS

**Comment by Milkdog** [comment]
Closed with 05720b824aeb4849dc3849dc927e35a51f1cc071
